# 言語設定
language: 'jp'
# 早期アクセス設定
early_access: false
# レビュー設定
reviews:
  # 高レベルの要約を提供するかどうか
  high_level_summary: true
  # 詩のレビューを提供するかどうか
  poem: true
  # レビュー状況を提供するかどうか
  review_status: true
  # ウォークスルーを折りたたむかどうか
  collapse_walkthrough: false
  # パスフィルター設定
  path_filters:
    - '!**/.github/**'
    - '!**/.vscode/**'
    - '!**/dist/**'
    - '!**/build/**'
    - '!**/.husky/**'
    - '!**.json'
    - '!**.lock'
    - '!.gitignore'
  # パスごとの指示設定
  path_instructions:
    - path: '**.js, **.ts, **.jsx, **.tsx'
      instructions: |
        "あなたはWebエンジニアです。
        あなたの目的は、非常に経験豊富なWebエンジニアとして機能し、コードの一部を徹底的にレビューし、
        以下のようなキーエリアを改善するためのコードスニペットを提案することです：
        - ロジック
        - セキュリティ
        - パフォーマンス
        - データ競合
        - 一貫性
        - エラー処理
        - 保守性
        - モジュール性
        - 複雑性
        - 最適化
        - ベストプラクティス: DRY, SOLID, KISS
        - テスト
        些細なコードスタイルの問題や、コメント・ドキュメントの欠落についてはコメントしないでください。
        重要な問題を特定し、解決して全体的なコード品質を向上させることを目指してくださいが、細かい問題は意図的に無視してください。
        なるべく簡潔に書いてください。"
    - path: '**.spec.js, **.spec.ts, **.spec.jsx, **.spec.tsx'
      instructions: |
        "テストコードをレビューしてください。
        あなたの目的は、テストコードの品質を向上させることです。
        以下のようなキーエリアを改善するためのコードスニペットを提案してください：
        - テストカバレッジ
        - テストの信頼性
        - テストの読みやすさ
        - テストの保守性
        - テストのベストプラクティス
        - テストのパフォーマンス
        - テストの一貫性
        - テストの最適化
        - テストのモジュール性
        - テストの複雑性
        - テストのベストプラクティス: DRY, SOLID, KISS
        なるべく簡潔に書いてください。"
  # 自動レビュー設定
  auto_review:
    enabled: true
    # タイトルにこれらのキーワードが含まれている場合は無視する
    ignore_title_keywords:
      - 'WIP'
      - 'DO NOT MERGE'
    # ドラフト設定
    drafts: false
    # ベースブランチ設定
    base_branches:
      - 'main'
      - 'develop'
      - 'feat/*'
# チャット設定
chat:
  # 自動返信設定
  auto_reply: true
